# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r:
  - release
  - oldrel
  - devel

sudo: required
dist: trusty

warnings_are_errors: true

latex: false

